<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Newbie Web</title>
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.4/css/bootstrap.min.css">
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css">
        <link rel="stylesheet" href="css/style.css">
    </head>
    <body>
		<header>
			<div class="container">
				<div class="jumbotron">
					<h1>Newbie Web</h1> 
					<p>Pour tout apprendre sur la programmtion web.</p> 
				</div>
			</div>
		</header>
		
		<div class="corps">
			<button type="button" id="signIn" class="btn btn-primary btn-lg">Connexion</button>
			<button type="button" id="signUp" class="btn btn-primary btn-lg">Enregistrez-vous</button>
		</div>

		<footer>
			<div class="gauche">
				<h4 class="footTitle">A propos</h4>
				<p>
					Cette application a été créée pour les débutants en développement web.</br>
					
				</p>
			</div>
			<div class="milieu">
				<button type="button" id="contact" class="btn btn-primary btn-lg">Contactez-nous</button>
			</div>
			<div class="droite">
				<h4 class="footTitle">Restez au courant</h4>
				<a class="btn btn-social-icon">
					<span class="fa fa-facebook"></span>
				</a>
				<a class="btn btn-social-icon">
					<span class="fa fa-google-plus"></span>
				</a>
				<a class="btn btn-social-icon">
					<span class="fa fa-twitter"></span>
				</a>
				<a class="btn btn-social-icon">
					<span class="fa fa-dribbble"></span>
				</a>
				<a class="btn btn-social-icon">
					<span class="fa fa-linkedin"></span>
				</a>
			</div>
		</footer>
    </body>
</html>
